export const defaultConfig = {
	text: 'Glowio',
	particleSize: 5,
	fontSize: 150,
	particlePer100Pixels: 50,
	color: '#00ff90',
	colorVariation: 5,
	opacityMin: 1,
	opacityMax: 50,

	horzSineEnabled: false,
	horzSineAmplitude: 10,
	horzSinePeriod: 100,
	horzSineRandomizeAmplitude: false,
	horzSineModulo: false,
	horzSineDelay: "offsetY",

	vertSineEnabled: false,
	vertSineAmplitude: 10,
	vertSinePeriod: 100,
	vertSineRandomizeAmplitude: false,
	vertSineModulo: false,
	vertSineDelay: "offsetX",

	horzTanEnabled: false,
	horzTanAmplitude: 10,
	horzTanPeriod: 100,
	horzTanRandomizeAmplitude: false,
	horzTanModulo: false,
	horzTanDelay: "offsetY",

	vertTanEnabled: false,
	vertTanAmplitude: 10,
	vertTanPeriod: 100,
	vertTanRandomizeAmplitude: false,
	vertTanModulo: false,
	vertTanDelay: "offsetX",
};