export const predefinedConfigs = {
	shimmering: {
		particleSize: 10,
		fontSize: 150,
		particlePer100Pixels: 140,
		color: '#4bf5fa',
		colorVariation: 81,
		opacityMin: 1,
		opacityMax: 50,
		horzSineEnabled: true,
		horzSineAmplitude: 50,
		horzSinePeriod: 10,
		horzSineRandomizeAmplitude: false,
		horzSineDelay: 'offsetX',
		vertSineEnabled: false,
		vertSineAmplitude: 100,
		vertSinePeriod: 107,
		vertSineRandomizeAmplitude: false,
		vertSineDelay: 'offsetY',
		name: 'shimmering',
	},
	'white noise': {
		particleSize: 7,
		fontSize: 150,
		particlePer100Pixels: 140,
		color: '#ffffff',
		colorVariation: 96,
		opacityMin: 1,
		opacityMax: 50,
		horzSineEnabled: true,
		horzSineAmplitude: 50,
		horzSinePeriod: 13,
		horzSineRandomizeAmplitude: true,
		horzSineDelay: 'offsetX',
		vertSineEnabled: false,
		vertSineAmplitude: 100,
		vertSinePeriod: 107,
		vertSineRandomizeAmplitude: false,
		vertSineDelay: 'offsetY',
		name: 'white noise',
	},
	'whirling cloth': {
		particleSize: 10,
		fontSize: 150,
		particlePer100Pixels: 170,
		color: '#ffffff',
		colorVariation: 10,
		opacityMin: 1,
		opacityMax: 50,
		horzSineEnabled: true,
		horzSineAmplitude: 7,
		horzSinePeriod: 50,
		horzSineRandomizeAmplitude: false,
		horzSineDelay: 'offsetY',
		vertSineEnabled: true,
		vertSineAmplitude: 23,
		vertSinePeriod: 65,
		vertSineRandomizeAmplitude: false,
		vertSineDelay: 'offsetY',
		name: 'whirling cloth',
	},
	squarish: {
		particleSize: 10,
		fontSize: 150,
		particlePer100Pixels: 170,
		color: '#ffffff',
		colorVariation: 10,
		opacityMin: 1,
		opacityMax: 50,
		horzSineEnabled: true,
		horzSineAmplitude: 20,
		horzSinePeriod: 50,
		horzSineRandomizeAmplitude: false,
		horzSineDelay: 'offsetX',
		vertSineEnabled: true,
		vertSineAmplitude: 20,
		vertSinePeriod: 65,
		vertSineRandomizeAmplitude: false,
		vertSineDelay: 'offsetY',
		name: 'squarish',
	},
};
