export const predefinedConfigs = {
	'under water': {
		particleSize: 20,
		fontSize: 150,
		particlePer100Pixels: 140,
		color: '#0000f9',
		colorVariation: 32,
		opacityMin: 1,
		opacityMax: 10,
		horzSineEnabled: true,
		horzSineAmplitude: 10,
		horzSinePeriod: 90,
		horzSineRandomizeAmplitude: false,
		horzSineDelay: 'offsetY',
		vertSineEnabled: false,
		vertSineAmplitude: 100,
		vertSinePeriod: 107,
		vertSineRandomizeAmplitude: false,
		vertSineDelay: 'offsetY',
		name: 'under water',
	},
	fire: {
		particleSize: 25,
		fontSize: 150,
		particlePer100Pixels: 50,
		color: '#e10000',
		colorVariation: 70,
		opacityMin: 1,
		opacityMax: 10,
		horzSineEnabled: false,
		horzSineAmplitude: 10,
		horzSinePeriod: 90,
		horzSineRandomizeAmplitude: false,
		horzSineDelay: 'offsetY',
		vertSineEnabled: true,
		vertSineAmplitude: 20,
		vertSinePeriod: 12,
		vertSineRandomizeAmplitude: true,
		vertSineDelay: 'offsetX',
		name: 'fire',
	},
	'3d': {
		particleSize: 15,
		fontSize: 150,
		particlePer100Pixels: 120,
		color: '#d7d7d7',
		colorVariation: 14,
		opacityMin: 1,
		opacityMax: 100,
		horzSineEnabled: true,
		horzSineAmplitude: 100,
		horzSinePeriod: 200,
		horzSineRandomizeAmplitude: false,
		horzSineDelay: 'offsetX',
		vertSineEnabled: false,
		vertSineAmplitude: 100,
		vertSinePeriod: 107,
		vertSineRandomizeAmplitude: false,
		vertSineDelay: 'offsetY',
		name: '3d',
	},
	'whirling cloth': {
		particleSize: 10,
		fontSize: 150,
		particlePer100Pixels: 170,
		color: '#ffffff',
		colorVariation: 10,
		opacityMin: 1,
		opacityMax: 50,
		horzSineEnabled: true,
		horzSineAmplitude: 7,
		horzSinePeriod: 50,
		horzSineRandomizeAmplitude: false,
		horzSineDelay: 'offsetY',
		vertSineEnabled: true,
		vertSineAmplitude: 23,
		vertSinePeriod: 65,
		vertSineRandomizeAmplitude: false,
		vertSineDelay: 'offsetY',
		name: 'whirling cloth',
	},
	shimmering: {
		particleSize: 10,
		fontSize: 150,
		particlePer100Pixels: 140,
		color: '#4bf5fa',
		colorVariation: 81,
		opacityMin: 1,
		opacityMax: 50,
		horzSineEnabled: true,
		horzSineAmplitude: 50,
		horzSinePeriod: 10,
		horzSineRandomizeAmplitude: false,
		horzSineDelay: 'offsetX',
		vertSineEnabled: false,
		vertSineAmplitude: 100,
		vertSinePeriod: 107,
		vertSineRandomizeAmplitude: false,
		vertSineDelay: 'offsetY',
		name: 'shimmering',
	},
	'white noise': {
		particleSize: 7,
		fontSize: 150,
		particlePer100Pixels: 140,
		color: '#ffffff',
		colorVariation: 96,
		opacityMin: 1,
		opacityMax: 50,
		horzSineEnabled: true,
		horzSineAmplitude: 50,
		horzSinePeriod: 13,
		horzSineRandomizeAmplitude: true,
		horzSineDelay: 'offsetX',
		vertSineEnabled: false,
		vertSineAmplitude: 100,
		vertSinePeriod: 107,
		vertSineRandomizeAmplitude: false,
		vertSineDelay: 'offsetY',
		name: 'white noise',
	},
	squarish: {
		particleSize: 10,
		fontSize: 150,
		particlePer100Pixels: 170,
		color: '#ffffff',
		colorVariation: 10,
		opacityMin: 1,
		opacityMax: 50,
		horzSineEnabled: true,
		horzSineAmplitude: 20,
		horzSinePeriod: 50,
		horzSineRandomizeAmplitude: false,
		horzSineDelay: 'offsetX',
		vertSineEnabled: true,
		vertSineAmplitude: 20,
		vertSinePeriod: 65,
		vertSineRandomizeAmplitude: false,
		vertSineDelay: 'offsetY',
		name: 'squarish',
	},
};
